#!/bin/bash

# Validate Render configuration before deployment
# Run this script locally before pushing to GitHub

set -e

echo "🔍 Validating Render deployment configuration..."
echo ""

# Check if render.yaml exists
if [ ! -f "render.yaml" ]; then
    echo "❌ render.yaml not found!"
    exit 1
fi
echo "✅ render.yaml found"

# Check if Dockerfile exists
if [ ! -f "Dockerfile" ]; then
    echo "❌ Dockerfile not found!"
    exit 1
fi
echo "✅ Dockerfile found"

# Check if package.json exists
if [ ! -f "package.json" ]; then
    echo "❌ package.json not found!"
    exit 1
fi
echo "✅ package.json found"

# Check if web dashboard exists
if [ ! -d "examples/web-dashboard" ]; then
    echo "❌ examples/web-dashboard directory not found!"
    exit 1
fi
echo "✅ Web dashboard directory found"

# Check if web dashboard package.json exists
if [ ! -f "examples/web-dashboard/package.json" ]; then
    echo "❌ examples/web-dashboard/package.json not found!"
    exit 1
fi
echo "✅ Web dashboard package.json found"

# Check if web dashboard server.js exists
if [ ! -f "examples/web-dashboard/server.js" ]; then
    echo "❌ examples/web-dashboard/server.js not found!"
    exit 1
fi
echo "✅ Web dashboard server.js found"

# Check if Prisma schema exists
if [ ! -f "prisma/schema.prisma" ]; then
    echo "❌ prisma/schema.prisma not found!"
    exit 1
fi
echo "✅ Prisma schema found"

# Check if .env.example exists
if [ ! -f ".env.example" ]; then
    echo "⚠️  .env.example not found (recommended for documentation)"
else
    echo "✅ .env.example found"
fi

# Validate environment variables in .env.example
echo ""
echo "📋 Required environment variables (add these in Render Dashboard):"
echo ""
echo "Backend API:"
echo "  - YOUTUBE_CLIENT_ID"
echo "  - YOUTUBE_CLIENT_SECRET"
echo "  - FACEBOOK_APP_ID"
echo "  - FACEBOOK_APP_SECRET"
echo "  - TIKTOK_CLIENT_KEY (optional)"
echo "  - TIKTOK_CLIENT_SECRET (optional)"
echo ""
echo "Security (auto-generated by Render):"
echo "  - JWT_SECRET"
echo "  - API_KEY_SALT"
echo ""

# Check if git is initialized
if [ ! -d ".git" ]; then
    echo "⚠️  Git repository not initialized"
    echo "   Run: git init && git add . && git commit -m 'Initial commit'"
else
    echo "✅ Git repository initialized"
fi

# Check if there are uncommitted changes
if ! git diff-index --quiet HEAD -- 2>/dev/null; then
    echo "⚠️  You have uncommitted changes"
    echo "   Run: git add . && git commit -m 'Your message'"
else
    echo "✅ No uncommitted changes"
fi

echo ""
echo "✅ Configuration validation complete!"
echo ""
echo "📝 Next steps:"
echo "   1. Commit and push to GitHub:"
echo "      git add ."
echo "      git commit -m 'Add Render deployment configuration'"
echo "      git push origin main"
echo ""
echo "   2. Deploy to Render:"
echo "      - Go to https://dashboard.render.com"
echo "      - Click 'New +' → 'Blueprint'"
echo "      - Select your repository"
echo "      - Click 'Apply'"
echo ""
echo "   3. Add environment variables in Render Dashboard"
echo ""
echo "📖 Full guide: See RENDER_DEPLOYMENT.md"
